name: openhd-ng-image-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install-dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get -y unzip qemu-user-static
    - name: build
      run: |
        ./build.sh
        mkdir deploy
        mv Open*.img deploy
    - name: upload-artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Open.HD-NG
        path: deploy
